#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

npm run check-format || (
  echo '❌ Failed prettier check.'
  false;
)

npm run check-lint || (
  echo '❌ ESLint check failed.'
  false;
)
